spring:
  application:
    name: jimmerDemo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.37.213:3307/fldg
    username: root
    password: hp51yYnbQqjBAWSj
    hikari:
      catalog: fldg


jimmer:
  language: kotlin
  show-sql: true
  pretty-sql: true
  database-validation-mode: WARNING
